from pathlib import Path
base=Path('/mnt/data/current_fix')
services=[
('01','Web Design','web-design.html','Distinctive interfaces that make a business feel credible, premium and memorable from the first click.','Interface direction','Responsive design','Conversion-focused layouts'),
('02','Development','development.html','Fast, responsive and dependable websites built with clean structure, strong performance and room to grow.','Frontend development','Performance engineering','Responsive builds'),
('03','Lead Generation','lead-generation.html','Turn attention into enquiries with clear journeys, persuasive calls to action and friction-free forms.','Conversion strategy','Lead forms','CTA architecture'),
('04','SEO Ready','seo-ready.html','Build a stronger search foundation with clean page structure, performance, metadata and crawl-friendly architecture.','Technical foundations','On-page structure','Performance'),
('05','Maintenance','maintenance.html','Keep your website secure, current and improving after launch with practical ongoing support.','Content updates','Technical fixes','Continuous improvement'),
('06','Hosting & Setup','hosting-setup.html','Get the launch infrastructure handled: domain, hosting, analytics, deployment and essential configuration.','Domain setup','Hosting deployment','Analytics & launch'),
]
for num,name,filename,desc,a,b,c in services:
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Nexora {name} services for ambitious businesses worldwide."><title>{name} — Nexora</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="services.css"></head><body><div class="grid"></div><header><a class="logo" href="index.html"><b>N</b>NEXORA</a><a class="back" href="index.html#services">← Back to Nexora</a></header><main><section class="hero"><div><div class="kicker">NEXORA / {num} — 06</div><h1>{name.replace('&','&amp;')}<br><em>that works.</em></h1><p>{desc}</p></div><div class="hero-art" data-number="{num}"><span class="art-label">SERVICE / {num}</span><div class="art-lines"></div></div></section><section class="content"><div class="kicker">WHAT THIS COVERS</div><h2>A sharper digital system<br>for your business.</h2><p>We treat {name.lower()} as part of the whole customer experience—not an isolated deliverable. The result should look distinctive, load quickly, communicate clearly and make the next action obvious.</p><div class="features"><article class="feature"><span>01</span><h3>{a}</h3><p>Built around your brand, audience and commercial goal.</p></article><article class="feature"><span>02</span><h3>{b}</h3><p>Designed to work smoothly across desktop, tablet and mobile.</p></article><article class="feature"><span>03</span><h3>{c}</h3><p>Connected to a practical workflow that supports growth after launch.</p></article></div></section><section class="cta"><h2>Let's build it<br>properly.</h2><a href="index.html#contact">Let's talk ↗</a></section></main><footer class="footer"><span>© 2026 Nexora Studio. All rights reserved.</span><span>Developed by Ibrahim Khurshid.</span></footer></body></html>'''
    (base/filename).write_text(html)
